// Generated by CHeaders2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: crsf_protocol.h (ExpressLRS) + crsf-wg wiki Packet-Types.md
// CRSF - TBS Crossfire serial protocol as spoken between a handset, the transmitter module, the receiver and the flight controller
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.crsf {
    /**
        <see cref = 'AIRSPEED'/>
        <see cref = 'ARDUPILOT_RESP'/>
        <see cref = 'ATTITUDE'/>
        <see cref = 'BARO_ALTITUDE'/>
        <see cref = 'BATTERY_SENSOR'/>
        <see cref = 'CELLS'/>
        <see cref = 'COMMAND'/>
        <see cref = 'DEVICE_INFO'/>
        <see cref = 'DEVICE_PING'/>
        <see cref = 'DISPLAYPORT_CMD'/>
        <see cref = 'ELRS_STATUS'/>
        <see cref = 'FLIGHT_MODE'/>
        <see cref = 'GPS'/>
        <see cref = 'GPS_TIME'/>
        <see cref = 'HANDSET'/>
        <see cref = 'HEARTBEAT'/>
        <see cref = 'KISS_REQ'/>
        <see cref = 'KISS_RESP'/>
        <see cref = 'LINK_RX_ID'/>
        <see cref = 'LINK_STATISTICS'/>
        <see cref = 'LINK_TX_ID'/>
        <see cref = 'MSP_REQ'/>
        <see cref = 'MSP_RESP'/>
        <see cref = 'MSP_WRITE'/>
        <see cref = 'PARAMETER_READ'/>
        <see cref = 'PARAMETER_SETTINGS_ENTRY'/>
        <see cref = 'PARAMETER_WRITE'/>
        <see cref = 'RC_CHANNELS_PACKED'/>
        <see cref = 'RPM'/>
        <see cref = 'SUBSET_RC_CHANNELS_PACKED'/>
        <see cref = 'TEMP'/>
        <see cref = 'VARIO'/>
        <see cref = 'elrsLinkStatistics'/>
        <see cref = 'mspVtxBandPacket'/>
        <see cref = 'mspVtxConfigPacket'/>
        <see cref = 'mspVtxPowerLevelPacket'/>
    */
    public interface CRSF {

        /**
        A CRSF payload is 60 bytes (58 for an extended frame), but a parameter value or a tunnelled MSP frame is
        chunked across several frames and reassembled, so the caps are raised past AdHoc's 255-item default.
        */
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ framing constants (#define / anonymous enum) ═════════════════════════

        /**
        Frame layout: [sync] [len] [type] [payload] [crc8], max 64 bytes; extended frames (type &gt;= 0x28) add [dest]
        [src] in front of the payload.
        */
        public struct Framing {
            public const long CRSF_CRC_POLY = 0xd5;
            public const long CRSF_MIN_PACKET_LEN = 4;
            public const long CRSF_MAX_PACKET_LEN = 64;
            public const long CRSF_SYNC_BYTE = 0xC8;
            /**
            length of SYNC and LEN fields
            */
            public const long CRSF_FRAME_NOT_COUNTED_BYTES = 2;
            public const long CRSF_FRAME_CRC_SIZE = 1;
            /**
            length of Extended Dest/Origin, TYPE and CRC fields combined
            */
            public const long CRSF_FRAME_LENGTH_EXT_TYPE_CRC = 4;
            public const long CRSF_TELEMETRY_LENGTH_INDEX = 1;
            public const long CRSF_TELEMETRY_TYPE_INDEX = 2;
            public const long CRSF_TELEMETRY_FIELD_ID_INDEX = 5;
            public const long CRSF_TELEMETRY_FIELD_CHUNK_INDEX = 6;
            public const long CRSF_TELEMETRY_CRC_LENGTH = 1;
            /**
            These flags are or'ed with the field type above to hide the field from the normal LUA view
            marked as hidden in all LUA responses
            */
            public const long CRSF_FIELD_HIDDEN = 0x80;
            /**
            Bits used in the byte following crsf_channels_t in the ExpressLRS extended CHANNELS_PACKED packet
            Armed status in Arm using Switch mode
            */
            public const long CRSF_CHANNELS_STATUS_ARMED = 1;
            /**
            Arm using CH5 if bit is set
            */
            public const long CRSF_CHANNELS_STATUS_ARMING_MODE_CH5 = 2;
            public const long CRSF_FRAME_TX_MSP_FRAME_SIZE = 58;
            public const long CRSF_FRAME_RX_MSP_FRAME_SIZE = 8;
            public const long CRSF_FRAME_ORIGIN_DEST_SIZE = 2;
        }

        /**
        CRSF channel value scale (172 = 988us, 992 = 1500us, 1811 = 2012us) and the matching microsecond limits.
        */
        public struct ChannelValue {
            /**
            stretch limit - changing this requires edits in getPwmFormData()
            */
            public const long US_CHANNEL_VALUE_MIN = 476;
            /**
            E.Limits min
            */
            public const long US_CHANNEL_VALUE_EXT_MIN = 880;
            /**
            standard min
            */
            public const long US_CHANNEL_VALUE_STD_MIN = 988;
            /**
            center
            */
            public const long US_CHANNEL_VALUE_CENTER = 1500;
            /**
            standard max
            */
            public const long US_CHANNEL_VALUE_STD_MAX = 2012;
            /**
            E.limits max
            */
            public const long US_CHANNEL_VALUE_EXT_MAX = 2120;
            /**
            stretch limit
            */
            public const long US_CHANNEL_VALUE_MAX = 2523;
            /**
            880us  -121.1% (with E.Limits on)
            */
            public const long CRSF_CHANNEL_VALUE_EXT_MIN = 0;
            /**
            988us  -100% (actual CRSF min is 0 with E.Limits on)
            */
            public const long CRSF_CHANNEL_VALUE_STD_MIN = 172;
            /**
            1000us
            */
            public const long CRSF_CHANNEL_VALUE_1000 = 191;
            /**
            1500us center
            */
            public const long CRSF_CHANNEL_VALUE_MID = 992;
            /**
            2000us
            */
            public const long CRSF_CHANNEL_VALUE_2000 = 1792;
            /**
            2012us +100% (actual CRSF max is 1984 with E.Limits on)
            */
            public const long CRSF_CHANNEL_VALUE_STD_MAX = 1811;
            /**
            2120us +121.1% (with E.Limits on)
            */
            public const long CRSF_CHANNEL_VALUE_EXT_MAX = 1984;
            /**
            used internally to indicate no channel value has been received
            */
            public const long CRSF_CHANNEL_VALUE_UNSET = 0xffff;
        }

        /**
        Sizes of MSP frames tunnelled through CRSF_FRAMETYPE_MSP_REQ / MSP_RESP / MSP_WRITE.
        */
        public struct MspTunnel {
            public const long CRSF_MSP_REQ_PAYLOAD_SIZE = 8;
            public const long CRSF_MSP_RESP_PAYLOAD_SIZE = 58;
            public const long MSP_SET_VTX_CONFIG_PAYLOAD_LENGTH = 15;
            public const long MSP_SET_VTXTABLE_BAND_PAYLOAD_LENGTH = 29;
            public const long MSP_SET_VTXTABLE_POWERLEVEL_PAYLOAD_LENGTH = 7;
        }

        // ═════════════════════════ enums ═════════════════════════

        /**
        Frame type byte; frames documented only in the crsf-wg wiki are appended after the header's entries.
        */
        enum crsf_frame_type {
            /**
            GPS position, ground speed, heading, altitude, satellite count
            */
            CRSF_FRAMETYPE_GPS = 0x2,
            CRSF_FRAMETYPE_GPS_TIME = 0x3,
            /**
            Vertical speed
            */
            CRSF_FRAMETYPE_VARIO = 0x7,
            /**
            Battery voltage, current, mAh, remaining percent
            */
            CRSF_FRAMETYPE_BATTERY_SENSOR = 0x8,
            /**
            Barometric altitude, vertical speed (optional)
            */
            CRSF_FRAMETYPE_BARO_ALTITUDE = 0x9,
            CRSF_FRAMETYPE_AIRSPEED = 0xA,
            /**
            (CRSFv3) Heartbeat
            */
            CRSF_FRAMETYPE_HEARTBEAT = 0xB,
            CRSF_FRAMETYPE_RPM = 0xC,
            CRSF_FRAMETYPE_TEMP = 0xD,
            CRSF_FRAMETYPE_CELLS = 0xE,
            /**
            Signal information. Uplink/Downlink RSSI, SNR, Link Quality (LQ), RF mode, transmit power
            */
            CRSF_FRAMETYPE_LINK_STATISTICS = 0x14,
            /**
            Channels data (both handset to TX and RX to flight controller)
            */
            CRSF_FRAMETYPE_RC_CHANNELS_PACKED = 0x16,
            /**
            Attitude: pitch, roll, yaw
            */
            CRSF_FRAMETYPE_ATTITUDE = 0x1E,
            /**
            Flight controller flight mode string
            */
            CRSF_FRAMETYPE_FLIGHT_MODE = 0x21,
            /**
            Sender requesting DEVICE_INFO from all destination devices
            Extended Header Frames, range: 0x28 to 0x96
            */
            CRSF_FRAMETYPE_DEVICE_PING = 0x28,
            /**
            Device name, firmware version, hardware version, serial number (PING response)
            */
            CRSF_FRAMETYPE_DEVICE_INFO = 0x29,
            /**
            Configuration item data chunk
            */
            CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY = 0x2B,
            /**
            Configuration item read request
            */
            CRSF_FRAMETYPE_PARAMETER_READ = 0x2C,
            /**
            Configuration item write request
            */
            CRSF_FRAMETYPE_PARAMETER_WRITE = 0x2D,
            /**
            !!Non Standard!! ExpressLRS good/bad packet count, status flags
            ELRS good/bad packet count and status flags
            */
            CRSF_FRAMETYPE_ELRS_STATUS = 0x2E,
            /**
            CRSF command execute
            */
            CRSF_FRAMETYPE_COMMAND = 0x32,
            /**
            Extended type used for OPENTX_SYNC
            */
            CRSF_FRAMETYPE_HANDSET = 0x3A,
            /**
            KISS request
            KISS frames
            */
            CRSF_FRAMETYPE_KISS_REQ = 0x78,
            /**
            KISS response
            */
            CRSF_FRAMETYPE_KISS_RESP = 0x79,
            /**
            MSP parameter request / command
            MSP commands
            response request using msp sequence as command
            */
            CRSF_FRAMETYPE_MSP_REQ = 0x7A,
            /**
            MSP parameter response chunk
            reply with 58 byte chunked binary
            */
            CRSF_FRAMETYPE_MSP_RESP = 0x7B,
            /**
            MSP parameter write
            write with 8 byte chunked binary (OpenTX outbound telemetry buffer limit)
            */
            CRSF_FRAMETYPE_MSP_WRITE = 0x7C,
            /**
            Ardupilot output?
            Ardupilot frames
            */
            CRSF_FRAMETYPE_ARDUPILOT_RESP = 0x80,
            /**
            (CRSFv3) Channels subset data
            (documented in the crsf-wg wiki only, not in crsf_protocol.h)
            */
            CRSF_FRAMETYPE_SUBSET_RC_CHANNELS_PACKED = 0x17,
            /**
            Receiver RSSI percent, power?
            (documented in the crsf-wg wiki only, not in crsf_protocol.h)
            */
            CRSF_FRAMETYPE_LINK_RX_ID = 0x1C,
            /**
            Transmitter RSSI percent, power, fps?
            (documented in the crsf-wg wiki only, not in crsf_protocol.h)
            */
            CRSF_FRAMETYPE_LINK_TX_ID = 0x1D,
            /**
            (CRSFv3) MSP DisplayPort control command
            (documented in the crsf-wg wiki only, not in crsf_protocol.h)
            */
            CRSF_FRAMETYPE_DISPLAYPORT_CMD = 0x7D,
        }

        // C enum with a single member: AdHoc rejects such enums, kept as a constants container.
        public struct crsf_command {
            public const long CRSF_COMMAND_SUBCMD_RX = 0x10;
        }

        enum crsf_subcommand {
            CRSF_COMMAND_SUBCMD_RX_BIND = 0x01,
            CRSF_COMMAND_MODEL_SELECT_ID = 0x05,
            CRSF_HANDSET_SUBCMD_TIMING = 0x10,
        }

        enum crsf_addr {
            CRSF_ADDRESS_BROADCAST = 0x00,
            CRSF_ADDRESS_USB = 0x10,
            CRSF_ADDRESS_BLUETOOTH_WIFI = 0x12,
            CRSF_ADDRESS_TBS_CORE_PNP_PRO = 0x80,
            CRSF_ADDRESS_RESERVED1 = 0x8A,
            CRSF_ADDRESS_CURRENT_SENSOR = 0xC0,
            CRSF_ADDRESS_GPS = 0xC2,
            CRSF_ADDRESS_TBS_BLACKBOX = 0xC4,
            CRSF_ADDRESS_FLIGHT_CONTROLLER = 0xC8,
            CRSF_ADDRESS_RESERVED2 = 0xCA,
            CRSF_ADDRESS_RACE_TAG = 0xCC,
            CRSF_ADDRESS_RADIO_TRANSMITTER = 0xEA,
            CRSF_ADDRESS_CRSF_RECEIVER = 0xEC,
            CRSF_ADDRESS_CRSF_TRANSMITTER = 0xEE,
            CRSF_ADDRESS_ELRS_LUA = 0xEF,
        }

        /**
        typedef struct crsf_addr_e asas;
        */
        enum crsf_value_type {
            CRSF_UINT8 = 0,
            CRSF_INT8 = 1,
            CRSF_UINT16 = 2,
            CRSF_INT16 = 3,
            CRSF_UINT32 = 4,
            CRSF_INT32 = 5,
            CRSF_UINT64 = 6,
            CRSF_INT64 = 7,
            CRSF_FLOAT = 8,
            CRSF_TEXT_SELECTION = 9,
            CRSF_STRING = 10,
            CRSF_FOLDER = 11,
            CRSF_INFO = 12,
            CRSF_COMMAND = 13,
            CRSF_VTX = 15,
            CRSF_OUT_OF_RANGE = 127,
        }

        // ═════════════════════════ frames (one pack per CRSF_FRAMETYPE) ═════════════════════════

        /**
        GPS position, ground speed, heading, altitude, satellite count
        C struct crsf_sensor_gps_t (crsf_protocol.h): CRSF_FRAMETYPE_GPS
        */
        class GPS {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x2;
            /**
            degree / 10`000`000
            */
            int latitude;
            /**
            degree / 10`000`000
            */
            int longitude;
            /**
            km/h / 10
            */
            ushort groundspeed;
            /**
            degree / 100
            */
            ushort gps_heading;
            /**
            meter ­1000m offset
            */
            ushort altitude;
            /**
            counter
            */
            byte satellites_in_use;
        }

        /**
        C struct crsf_sensor_gps_time_t (crsf_protocol.h): CRSF_FRAMETYPE_GPS_TIME
        */
        class GPS_TIME {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x3;
            short year;
            byte month;
            byte day;
            byte hour;
            byte minute;
            byte second;
            ushort millisecond;
        }

        /**
        Vertical speed
        C struct crsf_sensor_vario_t (crsf_protocol.h): CRSF_FRAMETYPE_VARIO
        */
        class VARIO {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x7;
            /**
            Vertical speed in cm/s, BigEndian
            */
            short verticalspd;
        }

        /**
        Battery voltage, current, mAh, remaining percent
        C struct crsf_sensor_battery_t (crsf_protocol.h): CRSF_FRAMETYPE_BATTERY_SENSOR
        */
        class BATTERY_SENSOR {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x8;
            /**
            mv * 100 BigEndian
            */
            [Bits(16), MinMax(0, 65535)] ushort voltage;
            /**
            ma * 100
            */
            [Bits(16), MinMax(0, 65535)] ushort current;
            /**
            mah
            */
            [Bits(24), MinMax(0, 16777215)] uint capacity;
            /**
            %
            */
            [Bits(8), MinMax(0, 255)] byte remaining;
        }

        /**
        Barometric altitude, vertical speed (optional)
        C struct crsf_sensor_baro_vario_t (crsf_protocol.h): CRSF_FRAMETYPE_BARO_ALTITUDE
        */
        class BARO_ALTITUDE {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x9;
            /**
            Altitude in decimeters + 10000dm, or Altitude in meters if high bit is set, BigEndian
            */
            ushort altitude;
            /**
            Vertical speed in cm/s, BigEndian
            */
            short verticalspd;
        }

        /**
        C struct crsf_sensor_airspeed_t (crsf_protocol.h): CRSF_FRAMETYPE_AIRSPEED
        */
        class AIRSPEED {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0xA;
            /**
            Airspeed in 0.1 * km/h (hectometers/h)
            */
            ushort speed;
        }

        /**
        (CRSFv3) Heartbeat
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_HEARTBEAT.md
        */
        class HEARTBEAT {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0xB;
            /**
            CRSFv3: address of the device that is alive, big-endian
            */
            ushort originDeviceAddress;
        }

        /**
        C struct crsf_sensor_rpm_t (crsf_protocol.h): CRSF_FRAMETYPE_RPM
        */
        class RPM {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0xC;
            /**
            Identifies the source of the RPM data (e.g., 0 = Motor 1, 1 = Motor 2, etc.)
            */
            byte source_id;
            /**
            1 - 19 RPM values with negative ones representing the motor spinning in reverse
            */
            [Bits(24), MinMax(-8388608, 8388607)] int rpm0;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm1;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm2;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm3;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm4;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm5;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm6;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm7;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm8;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm9;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm10;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm11;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm12;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm13;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm14;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm15;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm16;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm17;
            [Bits(24), MinMax(-8388608, 8388607)] int rpm18;
        }

        /**
        C struct crsf_sensor_temp_t (crsf_protocol.h): CRSF_FRAMETYPE_TEMP
        */
        class TEMP {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0xD;
            /**
            Identifies the source of the temperature data (e.g., 0 = FC including all ESCs, 1 = Ambient, etc.)
            */
            byte source_id;
            /**
            up to 20 temperature values in deci-degree (tenths of a degree) Celsius (e.g., 250 = 25.0°C, -50 = -5.0°C)
            */
            [D(20)] short[] temperature;
        }

        /**
        C struct crsf_sensor_cells_t (crsf_protocol.h): CRSF_FRAMETYPE_CELLS
        */
        class CELLS {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0xE;
            /**
            Identifies the source of the Main_battery data (e.g., 0 = battery 1, 1 = battery 2, etc.)
            */
            byte source_id;
            /**
            up to 29 cell values in a resolution of a thousandth of a Volt (e.g. 3.850V = 3850)
            */
            [D(29)] ushort[] cell;
        }

        /**
        Signal information. Uplink/Downlink RSSI, SNR, Link Quality (LQ), RF mode, transmit power
        C struct crsfLinkStatistics_t (crsf_protocol.h): 0x14 Link statistics
        Payload:
        uint8_t Uplink RSSI Ant. 1 ( dBm * -1 )
        uint8_t Uplink RSSI Ant. 2 ( dBm * -1 )
        uint8_t Uplink Package success rate / Link quality ( % )
        int8_t Uplink SNR ( db )
        uint8_t Diversity active antenna ( enum ant. 1 = 0, ant. 2 )
        uint8_t RF Mode ( enum 4fps = 0 , 50fps, 150hz)
        uint8_t Uplink TX Power ( enum 0mW = 0, 10mW, 25 mW, 100 mW, 500 mW, 1000 mW, 2000mW )
        uint8_t Downlink RSSI ( dBm * -1 )
        uint8_t Downlink package success rate / Link quality ( % )
        int8_t Downlink SNR ( db )
        Uplink is the connection from the ground to the UAV and downlink the opposite direction.
        */
        class LINK_STATISTICS {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x14;
            byte uplink_RSSI_1;
            byte uplink_RSSI_2;
            byte uplink_Link_quality;
            sbyte uplink_SNR;
            byte active_antenna;
            byte rf_Mode;
            byte uplink_TX_Power;
            byte downlink_RSSI_1;
            byte downlink_Link_quality;
            sbyte downlink_SNR;
        }

        /**
        Channels data (both handset to TX and RX to flight controller)
        C struct crsf_channels_t (crsf_protocol.h): Crossfire packed channel structure, each channel is 11 bits
        */
        class RC_CHANNELS_PACKED {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x16;
            [Bits(11), MinMax(0, 2047)] ushort ch0;
            [Bits(11), MinMax(0, 2047)] ushort ch1;
            [Bits(11), MinMax(0, 2047)] ushort ch2;
            [Bits(11), MinMax(0, 2047)] ushort ch3;
            [Bits(11), MinMax(0, 2047)] ushort ch4;
            [Bits(11), MinMax(0, 2047)] ushort ch5;
            [Bits(11), MinMax(0, 2047)] ushort ch6;
            [Bits(11), MinMax(0, 2047)] ushort ch7;
            [Bits(11), MinMax(0, 2047)] ushort ch8;
            [Bits(11), MinMax(0, 2047)] ushort ch9;
            [Bits(11), MinMax(0, 2047)] ushort ch10;
            [Bits(11), MinMax(0, 2047)] ushort ch11;
            [Bits(11), MinMax(0, 2047)] ushort ch12;
            [Bits(11), MinMax(0, 2047)] ushort ch13;
            [Bits(11), MinMax(0, 2047)] ushort ch14;
            [Bits(11), MinMax(0, 2047)] ushort ch15;
            /**
            ExpressLRS &gt;= 4.0 / EdgeTX 2.11: optional trailing byte, 0 = disarmed, 1 = armed; absent in the 22-byte
            legacy frame (wiki CRSF_FRAMETYPE_RC_CHANNELS_PACKED.md)
            */
            byte? armStatus;
        }

        /**
        Attitude: pitch, roll, yaw
        C struct crsf_sensor_attitude_t (crsf_protocol.h): CRSF_FRAMETYPE_ATTITUDE
        */
        class ATTITUDE {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x1E;
            /**
            radians * 10000
            */
            short pitch;
            /**
            radians * 10000
            */
            short roll;
            /**
            radians * 10000
            */
            short yaw;
        }

        /**
        Flight controller flight mode string
        C struct crsf_flight_mode_t (crsf_protocol.h): CRSF_FRAMETYPE_FLIGHT_MODE
        */
        class FLIGHT_MODE {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x21;
            [D(+16)] string flight_mode;
        }

        /**
        Sender requesting DEVICE_INFO from all destination devices
        Extended Header Frames, range: 0x28 to 0x96
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_DEVICE_PING.md
        */
        [ExtendedHeader]
        class DEVICE_PING {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x28;
        }

        /**
        Device name, firmware version, hardware version, serial number (PING response)
        C struct deviceInformationPacket_t (crsf_protocol.h)
        */
        [ExtendedHeader]
        class DEVICE_INFO {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x29;
            /**
            null-terminated device name; EdgeTX/ExpressLRS limit it to 15 characters (wiki CRSF_FRAMETYPE_DEVICE_INFO.md)
            */
            [D(+16)] string displayName;
            uint serialNo;
            uint hardwareVer;
            uint softwareVer;
            /**
            number of field of params this device has
            */
            byte fieldCnt;
            byte parameterVersion;
        }

        /**
        Configuration item data chunk
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_PARAMETER_SETTINGS_ENTRY.md
        */
        [ExtendedHeader]
        class PARAMETER_SETTINGS_ENTRY {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x2B;
            byte fieldIndex;
            /**
            chunks still to come after this one
            */
            byte chunksRemaining;
            /**
            field index of the parent folder, 0 for top level
            */
            byte parent;
            /**
            low 7 bits: crsf_value_type; high bit: hidden
            */
            byte typeAndHidden;
            /**
            parameter name, null-terminated
            */
            [D(+56)] string label;
            /**
            current/min/max/units for numeric types, index+options for SELECT, etc.
            */
            [D(56)] byte[,,] value;
        }

        /**
        Configuration item read request
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_PARAMETER_READ.md
        */
        [ExtendedHeader]
        class PARAMETER_READ {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x2C;
            /**
            0 is the root folder listing the top-level items, real fields start at 1
            */
            byte fieldIndex;
            /**
            chunk of the parameter description to fetch, starting at 0
            */
            byte chunkIndex;
        }

        /**
        Configuration item write request
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_PARAMETER_WRITE.md
        */
        [ExtendedHeader]
        class PARAMETER_WRITE {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x2D;
            byte fieldIndex;
            /**
            encoded like the value in PARAMETER_SETTINGS_ENTRY; size depends on the parameter type
            */
            [D(56)] byte[,,] value;
        }

        /**
        !!Non Standard!! ExpressLRS good/bad packet count, status flags
        ELRS good/bad packet count and status flags
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_ELRS_STATUS.md
        */
        [ExtendedHeader]
        class ELRS_STATUS {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x2E;
            /**
            failed-CRC packets in the past second
            */
            byte packetsBad;
            /**
            good packets in the past second
            */
            ushort packetsGood;
            /**
            0x01 connected, 0x04 model mismatch, 0x08 armed
            */
            byte flags;
            /**
            display message for the Lua
            */
            [D(+52)] string message;
        }

        /**
        CRSF command execute
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_COMMAND.md
        */
        [ExtendedHeader]
        class COMMAND {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x32;
            /**
            crsf_command: 0x10 receiver, 0x0A general
            */
            byte realm;
            /**
            crsf_subcommand
            */
            byte subcommand;
            [D(54)] byte[,,] payload;
            /**
            second CRC, poly 0xBA, over type..payload; transitional parsers accept its absence
            */
            byte crc8ba;
        }

        /**
        Extended type used for OPENTX_SYNC
        C struct crsf_sync_packet_t (crsf_protocol.h)
        */
        [ExtendedHeader]
        class HANDSET {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x3A;
            byte subType;
            /**
            Big-Endian
            */
            uint rate;
            /**
            Big-Endian
            */
            uint offset;
        }

        /**
        KISS request
        KISS frames
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_KISS_REQ.md
        */
        [ExtendedHeader]
        class KISS_REQ {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x78;
            /**
            KISS request, layout not documented
            */
            [D(58)] byte[,,] payload;
        }

        /**
        KISS response
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_KISS_RESP.md
        */
        [ExtendedHeader]
        class KISS_RESP {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x79;
            /**
            KISS response, layout not documented
            */
            [D(58)] byte[,,] payload;
        }

        /**
        MSP parameter request / command
        MSP commands
        response request using msp sequence as command
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_MSP_REQ.md
        */
        [ExtendedHeader]
        class MSP_REQ {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x7A;
            /**
            MSPv2 flags: version, begin/end of frame, error
            */
            ushort flags;
            /**
            MSP command id
            */
            ushort Function;
            ushort payloadLength;
            [D(52)] byte[,,] payload;
        }

        /**
        MSP parameter response chunk
        reply with 58 byte chunked binary
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_MSP_RESP.md
        */
        [ExtendedHeader]
        class MSP_RESP {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x7B;
            ushort flags;
            ushort Function;
            ushort payloadLength;
            /**
            58-byte chunks
            */
            [D(52)] byte[,,] payload;
        }

        /**
        MSP parameter write
        write with 8 byte chunked binary (OpenTX outbound telemetry buffer limit)
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_MSP_WRITE.md
        */
        [ExtendedHeader]
        class MSP_WRITE {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x7C;
            ushort flags;
            ushort Function;
            ushort payloadLength;
            /**
            8-byte chunks (OpenTX outbound telemetry buffer limit)
            */
            [D(52)] byte[,,] payload;
        }

        /**
        Ardupilot output?
        Ardupilot frames
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_ARDUPILOT_RESP.md
        */
        [ExtendedHeader]
        class ARDUPILOT_RESP {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x80;
            /**
            ArduPilot passthrough, layout not documented
            */
            [D(58)] byte[,,] payload;
        }

        /**
        (CRSFv3) Channels subset data
        (documented in the crsf-wg wiki only, not in crsf_protocol.h)
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_SUBSET_RC_CHANNELS_PACKED.md
        */
        class SUBSET_RC_CHANNELS_PACKED {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x17;
            /**
            bits 0-4 first channel number, bits 5-6 resolution (0=10, 1=11, 2=12, 3=13 bits/channel), bit 7 reserved
            */
            byte configByte;
            /**
            channel values packed at the declared resolution, count implied by the frame length
            */
            [D(59)] byte[,,] channelData;
        }

        /**
        Receiver RSSI percent, power?
        (documented in the crsf-wg wiki only, not in crsf_protocol.h)
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_LINK_RX_ID.md
        */
        class LINK_RX_ID {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x1C;
            /**
            downlink RSSI, dBm * -1
            */
            byte rssiDbm;
            byte rssiPercent;
            byte linkQuality;
            sbyte snr;
            byte rfPowerIndex;
        }

        /**
        Transmitter RSSI percent, power, fps?
        (documented in the crsf-wg wiki only, not in crsf_protocol.h)
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_LINK_TX_ID.md
        */
        class LINK_TX_ID {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x1D;
            /**
            uplink RSSI, dBm * -1
            */
            byte rssiDbm;
            byte rssiPercent;
            /**
            0 may signal a disconnected state
            */
            byte linkQuality;
            sbyte snr;
            /**
            not currently populated
            */
            byte rfPower;
            /**
            packet rate / 10, e.g. 33 for 333Hz
            */
            byte packetRateFps10;
        }

        /**
        (CRSFv3) MSP DisplayPort control command
        (documented in the crsf-wg wiki only, not in crsf_protocol.h)
        Payload transcribed from the crsf-wg wiki page CRSF_FRAMETYPE_DISPLAYPORT_CMD.md
        */
        [ExtendedHeader]
        class DISPLAYPORT_CMD {
            // CRSF frame type byte - the source protocol's identity, not this pack's AdHoc id.
            public const int frame_type = 0x7D;
            /**
            1 UPDATE, 2 CLEAR, 3 OPEN, 4 CLOSE, 5 POLL
            */
            byte subcommand;
            /**
            UPDATE: batch id/flags (0x80 first, 0x40 last chunk), index, RLE MSP DisplayPort data
            */
            [D(57)] byte[,,] data;
        }

        // ═════════════════════════ other structs of crsf_protocol.h ═════════════════════════

        /**
        https://github.com/betaflight/betaflight/blob/master/src/main/msp/msp.c#L1949
        C struct mspVtxConfigPacket_t
        */
        class mspVtxConfigPacket {
            byte vtxType;
            byte band;
            byte channel;
            byte power;
            byte pitmode;
            ushort freq;
            byte deviceIsReady;
            byte lowPowerDisarm;
            ushort pitModeFreq;
            byte vtxTableAvailable;
            byte bands;
            byte channels;
            byte powerLevels;
        }

        /**
        C struct mspVtxPowerLevelPacket_t
        */
        class mspVtxPowerLevelPacket {
            byte powerLevel;
            ushort powerValue;
            byte powerLabelLength;
            [D(3)] byte[] label;
        }

        /**
        C struct mspVtxBandPacket_t
        */
        class mspVtxBandPacket {
            byte band;
            byte bandNameLength;
            [D(8)] byte[] bandName;
            byte bandLetter;
            byte isFactoryBand;
            byte channels;
            [D(8)] ushort[] channel;
        }

        /**
        C struct elrsLinkStatistics_t
        */
        class elrsLinkStatistics : LINK_STATISTICS {
            byte downlink_RSSI_2;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The RF link between transmitter module and receiver is transparent to CRSF frames, so the demo
        // models the two ends of the conversation: the handset (EdgeTX) and the flight controller.

        // EdgeTX / OpenTX radio with the transmitter module
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Handset : Host { }

        // Betaflight / iNav / ArduPilot behind the receiver
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct FlightController : Host { }

        interface CrsfLink : Connects<Handset, FlightController> {
            // Telemetry items flow from the vehicle to the handset.
            [____________r<(GPS, GPS_TIME, VARIO, BATTERY_SENSOR, BARO_ALTITUDE, AIRSPEED, RPM, TEMP, CELLS, ATTITUDE, FLIGHT_MODE, LINK_RX_ID, LINK_TX_ID)>]
            struct Telemetry { }
            // Channel data flows from the handset to the vehicle.
            [l____________<(RC_CHANNELS_PACKED, SUBSET_RC_CHANNELS_PACKED)>]
            struct Control { }
            // Link statistics, heartbeat and every extended-header frame (ping/info, parameters, commands, MSP tunnel) go both ways.
            [_____lr_____<(HEARTBEAT, LINK_STATISTICS, DEVICE_PING, DEVICE_INFO, PARAMETER_SETTINGS_ENTRY, PARAMETER_READ, PARAMETER_WRITE, ELRS_STATUS, COMMAND, HANDSET, KISS_REQ, KISS_RESP, MSP_REQ, MSP_RESP, MSP_WRITE, ARDUPILOT_RESP, DISPLAYPORT_CMD)>]
            struct Extended { }
        }

        // ═════════════════════════ metadata attributes ═════════════════════════

        /** Width of the C bit-field the value occupies in the packed on-the-wire struct. */
        public class BitsAttribute : Attribute { public BitsAttribute(int width) { } }

        /** Extended-header frame (type &gt;= 0x28): [dest] [src] address bytes precede the payload. */
        public class ExtendedHeaderAttribute : Attribute { }

    }
}
